<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UnsrcEmailForm\Module'                   => __DIR__ . '/Module.php',
    'UnsrcEmailForm\Factory\EmailFormFactory' => __DIR__ . '/src/UnsrcEmailForm/Factory/EmailFormFactory.php',
    'UnsrcEmailForm\Service\EmailForm'        => __DIR__ . '/src/UnsrcEmailForm/Service/EmailForm.php',
    'UnsrcEmailForm\Plugin\ProcessForm'       => __DIR__ . '/src/UnsrcEmailForm/Plugin/ProcessForm.php',
    'UnsrcEmailForm\Model\SimpleEmailForm'    => __DIR__ . '/src/UnsrcEmailForm/Model/SimpleEmailForm.php',
    'UnsrcEmailForm\Helper\RenderForm'        => __DIR__ . '/src/UnsrcEmailForm/Helper/RenderForm.php',
);
